# ActiveRecord Database Configuration
development:
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  user: postgres
  database: midiservice_development

test:
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  user: postgres
  database: midiservice_test

production:
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  user: postgres
  database: midiservice_production
